create table countries (
        id integer generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );
    create table user_info (
            email_verified boolean not null,
            id integer generated by default as identity,
            create_at timestamp(6),
            updated_at timestamp(6),
            email varchar(255),
            family_name varchar(255),
            given_name varchar(255),
            user_id varchar(255),
            primary key (id)
        )